version: '3.7'

services:
  movie_service:
    build: ./movie-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./movie-service/:/app/
    ports:
      - 8001:8000
    environment:
      - DATABASE_URI=mysql://movie:movie@movie_db:3306/movie
      - CAST_SERVICE_HOST_URL=http://cast_service:8000/api/v1/casts/
    depends_on:
      - movie_db

  movie_db:
    container_name: movie_db-db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: movie
      MYSQL_PASSWORD: movie
      TZ: "Asia/Tokyo"
    tty: true
    volumes:
      - mysql_data_movie:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d

    # movie_db:
    # image: postgres:12.1-alpine
    # volumes:
    #   - postgres_data_movie:/var/lib/postgresql/data/
    # environment:
    #   - POSTGRES_USER=movie_db_username
    #   - POSTGRES_PASSWORD=movie_db_password
    #   - POSTGRES_DB=movie_db_dev

  nginx:
    # image: nginx:latest
    build: ./nginx
    ports:
      - "80:80"
    # command: rm /etc/nginx/conf.d/django_nginx.conf
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - cast_service
      - movie_service

volumes:
  mysql_data_movie:
  mysql_data_casts:
