CREATE DATABASE IF NOT EXISTS movie CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'movie' IDENTIFIED BY 'movie';
GRANT ALL ON *.* TO movie@'%' IDENTIFIED BY 'movie' WITH GRANT OPTION;

FLUSH PRIVILEGES;
